# Generated by Django 4.2.5 on 2023-10-04 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date_posted', models.DateField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='tasks')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='members')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='task.task')),
            ],
        ),
    ]
